### PR TITLE
maintain a cache of struct Process for currently active PIDs

### PR DESCRIPTION
**Pull request by themighty1**
decreases PID lookup time from ~100usec to ~5usec

### CODE REVIEW

**Comment by themighty1** [comment]
I've been running this patch for many days.

**Comment by gustavo-iniguez-goya** [comment]
:+1: 

I think we need to move:
https://github.com/evilsocket/opensnitch/pull/342/files#diff-7546f8dbef78d251cddff3e77702a4b99118887b0b94c354f4e55211658fc256R110

after here:
https://github.com/evilsocket/opensnitch/blob/f881cee5438b97213bac7477c4ce2267ee6a413b/daemon/procmon/parse.go#L91

Otherwise cached PIDs using audit won't be cached. Apart from that, it works great.

**Comment by themighty1** [comment]
I dont I think I understood your comment.
findProcessInActivePidsCache works only for method==proc
I dont see how it will affect the audit method?

**Comment by themighty1** [comment]
Oops, sorry, I wasnt thinking straight. Ignore my last comment.

**Comment by gustavo-iniguez-goya** [comment]
no problem :)

I think we can reorder FindProc() like these:
```
func FindProcess(pid int, interceptUnknown bool) *Process {
    if interceptUnknown && pid < 0 {
        return NewProcess(0, "")
    }

    if proc := findProcessInActivePidsCache(uint32(pid)); proc != nil {
        return proc
    }

    linkName := fmt.Sprint("/proc/", pid, "/exe")
    if _, err := os.Lstat(linkName); err != nil {
        return nil
    }

    if link, err := os.Readlink(linkName); err == nil {
        proc := NewProcess(pid, link)
        proc.readCwd()
        proc.readCmdline()

        if methodIsAudit() {
            if aevent := audit.GetEventByPid(pid); aevent != nil {
                audit.Lock.RLock()
                proc.Path = aevent.ProcPath
                proc.setCwd(aevent.ProcDir)
                audit.Lock.RUnlock()
                // if the proc dir contains non alhpa-numeric chars the field is empty
                if proc.CWD == "" {
                    proc.readCwd()
                }
            }
        }

        proc.readEnv()
        proc.cleanPath()

        addToActivePidsCache(uint32(pid), proc)
        return proc
    }
    return nil
}

```

and process.go, Init():

```
            go audit.Reader(auditConn, (chan<- audit.Event)(audit.EventChan))
+            go monitorActivePids()

```

**Comment by gustavo-iniguez-goya** [comment]
oops, nevermind, I've realized why I created a new Process{} if the method was audit. [We can't rely on /proc for anything](https://sysdig.com/blog/hiding-linux-processes-for-fun-and-profit/), if there's a better alternative.

**Comment by themighty1** [comment]
I was planning to revisit this PR today but I see it was merged.
So your initial suggestion was to let the audit method take advantage of this new active PIDs cache, right?
Honestly, I didn't get around to understanding how audit method works.

Does audit method rely on func newConnectionImpl()? We have to do the same /proc lookup for method "audit" as for method "proc" ? I'm sure I'm missing something. 

Does audit method keep a map of correlation between a PID and the IP-tuple from the connect() syscall? I could not find it.

**Comment by gustavo-iniguez-goya** [comment]
Sorry, I'd like to release a new version with latest changes ASAP. Your fix for VPNs and the fixes for regexp rules are very important.

> So your initial suggestion was to let the audit method take advantage of this new active PIDs cache, right?

Yes, we're creating a NewProcess() object on FindProcess() that it's not being cached:
https://github.com/evilsocket/opensnitch/blob/master/daemon/procmon/parse.go#L95
So it needs also to be cached.

The reason for exiting from FindProcess() before checking the `/proc/<pid>/exe` link and read the cmdline file is that by using audit we already received the path of the process from the kernel directly, via the audit framework. That's why it's a little bit safer/reliable to use it, but still, we need to lookup the inode of the connection under /proc. There's no way to match an outgoing connection against the received audit events. And the audit framework does not log the inode of a connection, nor the source port of it (only srcIP -> dstIP:port).

> Does audit method rely on func newConnectionImpl()?

Yes, it works in the same way than ftrace: 
https://github.com/evilsocket/opensnitch/blob/master/daemon/procmon/parse.go#L62

Since it reads events (connect(), socket(), etc), from a pipe, it also has its own cache of pids that open connections.

> Does audit method keep a map of correlation between a PID and the IP-tuple from the connect() syscall?

Yes: https://github.com/evilsocket/opensnitch/blob/master/daemon/procmon/audit/client.go#L175

**Comment by gustavo-iniguez-goya** [comment]
Actually, we read the events from the daemon auditd, not the kernel audit framework. We could work as that daemon, connecting directly to the kernel to read the events, but there can only be one process connected to the audit framework at a time, and as the auditd daemon comes preinstalled in many distros (suse, redhat, fedora...) we'd probably run into many problems.

**Comment by themighty1** [comment]
Thanks for explainin, it makes sense now.

**Pull request merged**
