### PR TITLE
makefile:

### PR DESCRIPTION
**Pull request by themighty1**
rename, remove unused targets
    trigger targets only when relevant files actually are changed
git:
    do not track files which are generated during make
github actions fix to not rely on a pre-built ui.pb.go

### CODE REVIEW

**Comment by themighty1** [comment]
@gustavo-iniguez-goya , any thoughts on this PR ?

**Comment by gustavo-iniguez-goya** [comment]
sorry @themighty1 , I ran into some issues when you pushed it (before 1.3.6 release). As the protocols are no longer on the branch, my scripts to create the packages failed.

But I've tested it again, and just executing `make protocol` before creating the packages resolves the problem.

**Comment by gustavo-iniguez-goya** [comment]
There's an error with the github action: https://github.com/evilsocket/opensnitch/runs/1953642591#step:4:58

Maybe we need to `make protocol`  before getting the dependencies? https://github.com/evilsocket/opensnitch/blob/master/.github/workflows/go.yml#L21

**Comment by themighty1** [comment]
Noted, thanks, will look into it.

**Pull request merged**
