### PR TITLE
fixes #439 - module namespace conflict

### LINKED ISSUE #439: opensnitch-ui / AttributeError: type object 'Config' has no attribute 'init'
Hello, I'm running into an issue on Ubuntu 20.04 after installing the deb packages for `1.3.6-1`

Recieving the following error
```
Loading translations: /usr/local/lib/python3.8/dist-packages/opensnitch/i18n locale: en_US
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 60, in <module>
    service = UIService(app, on_exit)
  File "/usr/local/lib/python3.8/dist-packages/opensnitch/service.py", line 43, in __init__
    self._cfg = Config.init()
AttributeError: type object 'Config' has no attribute 'init'
```

pip is showing these packages installed

```
# installed
unicode_slugify==0.1.3
grpcio==1.38.0
grpcio-tools==1.38.0
pyinotify==0.9.6
PyQt5==5.14.1
protobuf==3.17.3
```

Anybody have ideas on how to fix it?

I did try to compile the latest release candidate but got the same errors.

TIA! :)

### PR DESCRIPTION
**Pull request by shollingsworth**
Tested this out, and it should fix current and future module name conflicts for the `opensnitch-ui`

Cheers!

### CODE REVIEW

**Comment by gustavo-iniguez-goya** [comment]
Thank you @shollingsworth !

It seems that there's a exception when updating the stats:
`Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'`

Have you seen it on your system?

**Comment by shollingsworth** [comment]
> Thank you @shollingsworth !
> 
> It seems that there's a exception when updating the stats:
> `Ping exception: UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'`
> 
> Have you seen it on your system?

No, but ping doesn't work at all (except for the dns lookup)

I'm looking at the debug logs. I don't see the exception in the UI (cli output) , the UI OR the logs.

Reviewing the code to see why that might be. I do notice on some of the rule / event entries, it's showing attribute errors for rules.

**Comment by gustavo-iniguez-goya** [comment]
The error is not related to the ping command (or ICMP), it's a "ping" from the daemon to the GUI, via the gRPC protocol. Every second the daemon sends the events via this method (Ping):

https://github.com/evilsocket/opensnitch/blob/1c73a48b9c01b4656148c52b798ee7e3874b4923/ui/opensnitch/service.py#L440
https://github.com/evilsocket/opensnitch/blob/1c73a48b9c01b4656148c52b798ee7e3874b4923/daemon/ui/client.go#L261
https://github.com/evilsocket/opensnitch/blob/1c73a48b9c01b4656148c52b798ee7e3874b4923/proto/ui.proto#L8

For some reason it has stopped working on Ubuntu 16.04 (python 3.5, grpcio 1.16.0) and Debian Sid (python 3.9, grpcio 1.37.1).

The effect is that there're no events (on Debian Sid there're other issues really weird, like instanstiate an object and after that it's None again.. )

**Comment by shollingsworth** [comment]
OK, reproduced the error, has something to do with `protobuf`.
```
Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'
```

**Comment by shollingsworth** [comment]
@gustavo-iniguez-goya OK, Looks like it's fixed. I think the `ui_pbd2` import is suffering the same issue. It's importing as a global rather than relative to this project.

if there were others for these name in `PATH` it might work, it might not.
```
ui_pb2.py
ui_pb2_grpc.py
```

The last commit just changes the import to explicitly relative.

After that the exception messages went away.

**Comment by gustavo-iniguez-goya** [comment]
great @shollingsworth , now it's working fine.

Instead of changing the import manually, maybe a better way of doing it would be:
```
$ cd proto
$ mkdir opensnitch
$ python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. opensnitch/ui.proto
```

It generates this import that seems to work fine:
`from opensnitch import ui_pb2 as opensnitch_dot_ui__pb2`

The commando for generate the Go proto would be:
`protoc -I. opensnitch/ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/ --go_opt=paths=source_relative`

And there'll need to change import paths from `github.com/evilsocket/opensnitch/daemon/ui/protocol` to `github.com/evilsocket/opensnitch/daemon/ui/protocol/opensnitch`

**Comment by shollingsworth** [comment]
Cool, I didn't much like the Makefile hack tbh. I'll see if I can implement those changes in the next few days.

**Comment by gustavo-iniguez-goya** [comment]
thank you!

**Comment by BeTmAsTeR** [comment]
just installed the latest [opensnitch-git from AUR](https://aur.archlinux.org/packages/opensnitch-git/), still getting the same error

Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'

**Comment by shollingsworth** [comment]
> just installed the latest [opensnitch-git from AUR](https://aur.archlinux.org/packages/opensnitch-git/), still getting the same error
> 
> `Ping exception: UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest' `

@BeTmAsTeR try installing from latest master here, The version you linked to doesn't include the changes in this PR.

**Comment by shollingsworth** [comment]
@gustavo-iniguez-goya  I gave this a college try, but ran into a bunch of go import issues.

This part worked, but the go build stuff isn't referencing relative imports, so it didn't see anything existing in the current repo. I don't know enough about go to get much further on that front.

Here is the patch for the python generation stuff though.

```diff --git a/proto/Makefile b/proto/Makefile
index 2af601d..e6fd823 100644
--- a/proto/Makefile
+++ b/proto/Makefile
@@ -1,10 +1,10 @@
 all: ../daemon/ui/protocol/ui.pb.go ../ui/opensnitch/ui_pb2.py
 
-../daemon/ui/protocol/ui.pb.go: ui.proto
-       protoc -I. ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/ --go_opt=paths=source_relative
+../daemon/ui/protocol/ui.pb.go: opensnitch/ui.proto
+       protoc -I. opensnitch/ui.proto --go_out=plugins=grpc:../daemon/ui/protocol/ --go_opt=paths=source_relative
 
-../ui/opensnitch/ui_pb2.py: ui.proto
-       python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
+../ui/opensnitch/ui_pb2.py: opensnitch/ui.proto
+       python3 -m grpc_tools.protoc -I. --python_out=../ui --grpc_python_out=../ui opensnitch/ui.proto
 
 clean:
        @rm -rf ../daemon/ui/protocol/ui.pb.go
diff --git a/proto/ui.proto b/proto/opensnitch/ui.proto
similarity index 100%
rename from proto/ui.proto
rename to proto/opensnitch/ui.proto
```

**Pull request merged**
