### PR TITLE
add wiki

### PR DESCRIPTION
**Pull request by themighty1**

### CODE REVIEW

**Comment by themighty1** [comment]
Obviously, the failed check will be successful once merged, as it invokes evilsocket's github token.

**Comment by gustavo-iniguez-goya** [comment]
We have the other wiki on its own branch, wouldn't it be better to keep clean the master branch from wiki updates?

**Comment by themighty1** [comment]
Yes, please. If you could make a wiki branch.

**Comment by gustavo-iniguez-goya** [comment]
done!

**Comment by themighty1** [comment]
changed against new branch

**Pull request merged**
