### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zero77**
seting GOPATH=

### CODE REVIEW

**Comment by xenDE** [comment]
on debian 9:
sudo ln -s /usr/lib/go-1.8/ /usr/lib/go
export GOROOT=/usr/lib/go
export GOPATH=$HOME/src/goproj
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
# and insert the export's to .profile:
nano /home/$USER/.profile

**Comment by zero77** [comment]
@xenDE 
so add this to ~/.profile
>sudo ln -s /usr/lib/go-1.8/ /usr/lib/go
export GOROOT=/usr/lib/go
export GOPATH=$HOME/src/goproj
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

**Comment by zero77** [comment]
@xenDE 
I am trying to fix this build error.

> make[1]: Entering directory '/home/user/go/src/github.com/evilsocket/opensnitch/proto'
python3 -m grpc_tools.protoc -I. --python_out=../ui/opensnitch/ --grpc_python_out=../ui/opensnitch/ ui.proto
make[1]: Leaving directory '/home/user/go/src/github.com/evilsocket/opensnitch/proto'
make[1]: Entering directory '/home/user/go/src/github.com/evilsocket/opensnitch/daemon'
make[1]: dep: Command not found
Makefile:10: recipe for target 'deps' failed
make[1]: *** [deps] Error 127
make[1]: Leaving directory '/home/user/go/src/github.com/evilsocket/opensnitch/daemon'
Makefile:11: recipe for target 'daemon/opensnitchd' failed
make: *** [daemon/opensnitchd] Error 2

**Comment by zero77** [comment]
@xenDE 
I am using ubuntu 18.04 and this seems to work for me.
> sudo apt install golang-1.8

> sudo ln -s /usr/lib/go-1.8/ /usr/lib/go

> echo "export GOPATH=$HOME/go
export GOROOT=/usr/lib/go
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH" >> ~/.bashrc

.bashrc worked for me in ubuntu but i dont no if .profile will.
Either way it seams to be working now, thanks.

**Comment by xenDE** [comment]
~/.bashrc is only working if u use /bin/bash as shell.

better use .profile

u need to reopen your shell/terminal to take effect or execute the 3 exports in your shell.

but its ok, its now working for you.

**Pull request closed without merging**
